// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/pim.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeValue represents a typed attribute value
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "string", "number", "boolean", "date"
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_NumberValue
	//	*AttributeValue_BooleanValue
	//	*AttributeValue_DateValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_proto_pim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *AttributeValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type AttributeValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type AttributeValue_DateValue struct {
	DateValue string `protobuf:"bytes,5,opt,name=date_value,json=dateValue,proto3,oneof"` // ISO 8601 format
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_NumberValue) isAttributeValue_Value() {}

func (*AttributeValue_BooleanValue) isAttributeValue_Value() {}

func (*AttributeValue_DateValue) isAttributeValue_Value() {}

// Pagination metadata for list responses
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalItems    int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_pim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// ErrorResponse for API errors
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetail           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_pim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_proto_pim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Product represents a product in the PIM system
type Product struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                     `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Description   string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ProductTypeId string                     `protobuf:"bytes,5,opt,name=product_type_id,json=productTypeId,proto3" json:"product_type_id,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp     `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_pim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetProductTypeId() string {
	if x != nil {
		return x.ProductTypeId
	}
	return ""
}

func (x *Product) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProductCreateRequest for creating a new product
type ProductCreateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                     `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Description   string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProductTypeId string                     `protobuf:"bytes,4,opt,name=product_type_id,json=productTypeId,proto3" json:"product_type_id,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateRequest) Reset() {
	*x = ProductCreateRequest{}
	mi := &file_proto_pim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateRequest) ProtoMessage() {}

func (x *ProductCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateRequest.ProtoReflect.Descriptor instead.
func (*ProductCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{5}
}

func (x *ProductCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreateRequest) GetProductTypeId() string {
	if x != nil {
		return x.ProductTypeId
	}
	return ""
}

func (x *ProductCreateRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ProductUpdateRequest for updating a product
type ProductUpdateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProductTypeId string                     `protobuf:"bytes,3,opt,name=product_type_id,json=productTypeId,proto3" json:"product_type_id,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateRequest) Reset() {
	*x = ProductUpdateRequest{}
	mi := &file_proto_pim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateRequest) ProtoMessage() {}

func (x *ProductUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProductUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{6}
}

func (x *ProductUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdateRequest) GetProductTypeId() string {
	if x != nil {
		return x.ProductTypeId
	}
	return ""
}

func (x *ProductUpdateRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ProductListResponse for listing products
type ProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListResponse) Reset() {
	*x = ProductListResponse{}
	mi := &file_proto_pim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListResponse) ProtoMessage() {}

func (x *ProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListResponse.ProtoReflect.Descriptor instead.
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{7}
}

func (x *ProductListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductListResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Variant represents a product variant
type Variant struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                     `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku           string                     `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_proto_pim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{8}
}

func (x *Variant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Variant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Variant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Variant) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Variant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Variant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// VariantCreateRequest for creating a new variant
type VariantCreateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sku           string                     `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantCreateRequest) Reset() {
	*x = VariantCreateRequest{}
	mi := &file_proto_pim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantCreateRequest) ProtoMessage() {}

func (x *VariantCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantCreateRequest.ProtoReflect.Descriptor instead.
func (*VariantCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{9}
}

func (x *VariantCreateRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *VariantCreateRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// VariantUpdateRequest for updating a variant
type VariantUpdateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantUpdateRequest) Reset() {
	*x = VariantUpdateRequest{}
	mi := &file_proto_pim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantUpdateRequest) ProtoMessage() {}

func (x *VariantUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantUpdateRequest.ProtoReflect.Descriptor instead.
func (*VariantUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{10}
}

func (x *VariantUpdateRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// VariantListResponse for listing variants
type VariantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variants      []*Variant             `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantListResponse) Reset() {
	*x = VariantListResponse{}
	mi := &file_proto_pim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantListResponse) ProtoMessage() {}

func (x *VariantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantListResponse.ProtoReflect.Descriptor instead.
func (*VariantListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{11}
}

func (x *VariantListResponse) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

// MediaAsset represents an image or video asset
type MediaAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,3,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "image" or "video"
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,6,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,7,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAsset) Reset() {
	*x = MediaAsset{}
	mi := &file_proto_pim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAsset) ProtoMessage() {}

func (x *MediaAsset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAsset.ProtoReflect.Descriptor instead.
func (*MediaAsset) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{12}
}

func (x *MediaAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaAsset) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *MediaAsset) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *MediaAsset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaAsset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAsset) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *MediaAsset) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *MediaAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MediaAsset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MediaAssetCreateRequest for creating a media asset
type MediaAssetCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AltText       string                 `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAssetCreateRequest) Reset() {
	*x = MediaAssetCreateRequest{}
	mi := &file_proto_pim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAssetCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAssetCreateRequest) ProtoMessage() {}

func (x *MediaAssetCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAssetCreateRequest.ProtoReflect.Descriptor instead.
func (*MediaAssetCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{13}
}

func (x *MediaAssetCreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaAssetCreateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAssetCreateRequest) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *MediaAssetCreateRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

// MediaAssetUpdateRequest for updating a media asset
type MediaAssetUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AltText       string                 `protobuf:"bytes,1,opt,name=alt_text,json=altText,proto3" json:"alt_text,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,2,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAssetUpdateRequest) Reset() {
	*x = MediaAssetUpdateRequest{}
	mi := &file_proto_pim_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAssetUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAssetUpdateRequest) ProtoMessage() {}

func (x *MediaAssetUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAssetUpdateRequest.ProtoReflect.Descriptor instead.
func (*MediaAssetUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{14}
}

func (x *MediaAssetUpdateRequest) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *MediaAssetUpdateRequest) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

// MediaAssetListResponse for listing media assets
type MediaAssetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaAssets   []*MediaAsset          `protobuf:"bytes,1,rep,name=media_assets,json=mediaAssets,proto3" json:"media_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAssetListResponse) Reset() {
	*x = MediaAssetListResponse{}
	mi := &file_proto_pim_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAssetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAssetListResponse) ProtoMessage() {}

func (x *MediaAssetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAssetListResponse.ProtoReflect.Descriptor instead.
func (*MediaAssetListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{15}
}

func (x *MediaAssetListResponse) GetMediaAssets() []*MediaAsset {
	if x != nil {
		return x.MediaAssets
	}
	return nil
}

// ProductType represents a product type template
type ProductType struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AttributeDefinitions []*AttributeDefinition `protobuf:"bytes,4,rep,name=attribute_definitions,json=attributeDefinitions,proto3" json:"attribute_definitions,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProductType) Reset() {
	*x = ProductType{}
	mi := &file_proto_pim_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductType) ProtoMessage() {}

func (x *ProductType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductType.ProtoReflect.Descriptor instead.
func (*ProductType) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{16}
}

func (x *ProductType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductType) GetAttributeDefinitions() []*AttributeDefinition {
	if x != nil {
		return x.AttributeDefinitions
	}
	return nil
}

func (x *ProductType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AttributeDefinition defines an attribute schema
type AttributeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductTypeId string                 `protobuf:"bytes,2,opt,name=product_type_id,json=productTypeId,proto3" json:"product_type_id,omitempty"`
	AttributeName string                 `protobuf:"bytes,3,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // "string", "number", "boolean", "date"
	IsRequired    bool                   `protobuf:"varint,5,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_proto_pim_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{17}
}

func (x *AttributeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeDefinition) GetProductTypeId() string {
	if x != nil {
		return x.ProductTypeId
	}
	return ""
}

func (x *AttributeDefinition) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *AttributeDefinition) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeDefinition) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *AttributeDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ProductTypeCreateRequest for creating a product type
type ProductTypeCreateRequest struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AttributeDefinitions []*AttributeDefinitionInput `protobuf:"bytes,3,rep,name=attribute_definitions,json=attributeDefinitions,proto3" json:"attribute_definitions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProductTypeCreateRequest) Reset() {
	*x = ProductTypeCreateRequest{}
	mi := &file_proto_pim_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductTypeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTypeCreateRequest) ProtoMessage() {}

func (x *ProductTypeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTypeCreateRequest.ProtoReflect.Descriptor instead.
func (*ProductTypeCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{18}
}

func (x *ProductTypeCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductTypeCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductTypeCreateRequest) GetAttributeDefinitions() []*AttributeDefinitionInput {
	if x != nil {
		return x.AttributeDefinitions
	}
	return nil
}

// AttributeDefinitionInput for creating attribute definitions
type AttributeDefinitionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttributeName string                 `protobuf:"bytes,1,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	IsRequired    bool                   `protobuf:"varint,3,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDefinitionInput) Reset() {
	*x = AttributeDefinitionInput{}
	mi := &file_proto_pim_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinitionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinitionInput) ProtoMessage() {}

func (x *AttributeDefinitionInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinitionInput.ProtoReflect.Descriptor instead.
func (*AttributeDefinitionInput) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{19}
}

func (x *AttributeDefinitionInput) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *AttributeDefinitionInput) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeDefinitionInput) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

// ProductTypeUpdateRequest for updating a product type
type ProductTypeUpdateRequest struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AttributeDefinitions []*AttributeDefinitionInput `protobuf:"bytes,3,rep,name=attribute_definitions,json=attributeDefinitions,proto3" json:"attribute_definitions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProductTypeUpdateRequest) Reset() {
	*x = ProductTypeUpdateRequest{}
	mi := &file_proto_pim_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductTypeUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTypeUpdateRequest) ProtoMessage() {}

func (x *ProductTypeUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTypeUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProductTypeUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{20}
}

func (x *ProductTypeUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductTypeUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductTypeUpdateRequest) GetAttributeDefinitions() []*AttributeDefinitionInput {
	if x != nil {
		return x.AttributeDefinitions
	}
	return nil
}

// ProductTypeListResponse for listing product types
type ProductTypeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductTypes  []*ProductType         `protobuf:"bytes,1,rep,name=product_types,json=productTypes,proto3" json:"product_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductTypeListResponse) Reset() {
	*x = ProductTypeListResponse{}
	mi := &file_proto_pim_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductTypeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTypeListResponse) ProtoMessage() {}

func (x *ProductTypeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pim_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTypeListResponse.ProtoReflect.Descriptor instead.
func (*ProductTypeListResponse) Descriptor() ([]byte, []int) {
	return file_proto_pim_proto_rawDescGZIP(), []int{21}
}

func (x *ProductTypeListResponse) GetProductTypes() []*ProductType {
	if x != nil {
		return x.ProductTypes
	}
	return nil
}

var File_proto_pim_proto protoreflect.FileDescriptor

const file_proto_pim_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pim.proto\x12\x03pim\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x0eAttributeValue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12%\n" +
	"\rboolean_value\x18\x04 \x01(\bH\x00R\fbooleanValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x05 \x01(\tH\x00R\tdateValueB\a\n" +
	"\x05value\"\x7f\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"7\n" +
	"\rErrorResponse\x12&\n" +
	"\x05error\x18\x01 \x01(\v2\x10.pim.ErrorDetailR\x05error\"\xb0\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\adetails\x18\x03 \x03(\v2\x1d.pim.ErrorDetail.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fproduct_type_id\x18\x05 \x01(\tR\rproductTypeId\x12<\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\x1c.pim.Product.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x14ProductCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x0fproduct_type_id\x18\x04 \x01(\tR\rproductTypeId\x12I\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2).pim.ProductCreateRequest.AttributesEntryR\n" +
	"attributes\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"\x93\x02\n" +
	"\x14ProductUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12&\n" +
	"\x0fproduct_type_id\x18\x03 \x01(\tR\rproductTypeId\x12I\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2).pim.ProductUpdateRequest.AttributesEntryR\n" +
	"attributes\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"p\n" +
	"\x13ProductListResponse\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.pim.ProductR\bproducts\x12/\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x0f.pim.PaginationR\n" +
	"pagination\"\xd2\x02\n" +
	"\aVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12<\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x1c.pim.Variant.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x14VariantCreateRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12I\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2).pim.VariantCreateRequest.AttributesEntryR\n" +
	"attributes\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x14VariantUpdateRequest\x12I\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2).pim.VariantUpdateRequest.AttributesEntryR\n" +
	"attributes\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pim.AttributeValueR\x05value:\x028\x01\"?\n" +
	"\x13VariantListResponse\x12(\n" +
	"\bvariants\x18\x01 \x03(\v2\f.pim.VariantR\bvariants\"\xb6\x02\n" +
	"\n" +
	"MediaAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x03 \x01(\tR\tvariantId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x06 \x01(\tR\aaltText\x12#\n" +
	"\rdisplay_order\x18\a \x01(\x05R\fdisplayOrder\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x7f\n" +
	"\x17MediaAssetCreateRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12#\n" +
	"\rdisplay_order\x18\x04 \x01(\x05R\fdisplayOrder\"Y\n" +
	"\x17MediaAssetUpdateRequest\x12\x19\n" +
	"\balt_text\x18\x01 \x01(\tR\aaltText\x12#\n" +
	"\rdisplay_order\x18\x02 \x01(\x05R\fdisplayOrder\"L\n" +
	"\x16MediaAssetListResponse\x122\n" +
	"\fmedia_assets\x18\x01 \x03(\v2\x0f.pim.MediaAssetR\vmediaAssets\"\x98\x02\n" +
	"\vProductType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12M\n" +
	"\x15attribute_definitions\x18\x04 \x03(\v2\x18.pim.AttributeDefinitionR\x14attributeDefinitions\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xed\x01\n" +
	"\x13AttributeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fproduct_type_id\x18\x02 \x01(\tR\rproductTypeId\x12%\n" +
	"\x0eattribute_name\x18\x03 \x01(\tR\rattributeName\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1f\n" +
	"\vis_required\x18\x05 \x01(\bR\n" +
	"isRequired\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa4\x01\n" +
	"\x18ProductTypeCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12R\n" +
	"\x15attribute_definitions\x18\x03 \x03(\v2\x1d.pim.AttributeDefinitionInputR\x14attributeDefinitions\"\x7f\n" +
	"\x18AttributeDefinitionInput\x12%\n" +
	"\x0eattribute_name\x18\x01 \x01(\tR\rattributeName\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1f\n" +
	"\vis_required\x18\x03 \x01(\bR\n" +
	"isRequired\"\xa4\x01\n" +
	"\x18ProductTypeUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12R\n" +
	"\x15attribute_definitions\x18\x03 \x03(\v2\x1d.pim.AttributeDefinitionInputR\x14attributeDefinitions\"P\n" +
	"\x17ProductTypeListResponse\x125\n" +
	"\rproduct_types\x18\x01 \x03(\v2\x10.pim.ProductTypeR\fproductTypesB\x16Z\x14apidemo1/proto/pb;pbb\x06proto3"

var (
	file_proto_pim_proto_rawDescOnce sync.Once
	file_proto_pim_proto_rawDescData []byte
)

func file_proto_pim_proto_rawDescGZIP() []byte {
	file_proto_pim_proto_rawDescOnce.Do(func() {
		file_proto_pim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pim_proto_rawDesc), len(file_proto_pim_proto_rawDesc)))
	})
	return file_proto_pim_proto_rawDescData
}

var file_proto_pim_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_pim_proto_goTypes = []any{
	(*AttributeValue)(nil),           // 0: pim.AttributeValue
	(*Pagination)(nil),               // 1: pim.Pagination
	(*ErrorResponse)(nil),            // 2: pim.ErrorResponse
	(*ErrorDetail)(nil),              // 3: pim.ErrorDetail
	(*Product)(nil),                  // 4: pim.Product
	(*ProductCreateRequest)(nil),     // 5: pim.ProductCreateRequest
	(*ProductUpdateRequest)(nil),     // 6: pim.ProductUpdateRequest
	(*ProductListResponse)(nil),      // 7: pim.ProductListResponse
	(*Variant)(nil),                  // 8: pim.Variant
	(*VariantCreateRequest)(nil),     // 9: pim.VariantCreateRequest
	(*VariantUpdateRequest)(nil),     // 10: pim.VariantUpdateRequest
	(*VariantListResponse)(nil),      // 11: pim.VariantListResponse
	(*MediaAsset)(nil),               // 12: pim.MediaAsset
	(*MediaAssetCreateRequest)(nil),  // 13: pim.MediaAssetCreateRequest
	(*MediaAssetUpdateRequest)(nil),  // 14: pim.MediaAssetUpdateRequest
	(*MediaAssetListResponse)(nil),   // 15: pim.MediaAssetListResponse
	(*ProductType)(nil),              // 16: pim.ProductType
	(*AttributeDefinition)(nil),      // 17: pim.AttributeDefinition
	(*ProductTypeCreateRequest)(nil), // 18: pim.ProductTypeCreateRequest
	(*AttributeDefinitionInput)(nil), // 19: pim.AttributeDefinitionInput
	(*ProductTypeUpdateRequest)(nil), // 20: pim.ProductTypeUpdateRequest
	(*ProductTypeListResponse)(nil),  // 21: pim.ProductTypeListResponse
	nil,                              // 22: pim.ErrorDetail.DetailsEntry
	nil,                              // 23: pim.Product.AttributesEntry
	nil,                              // 24: pim.ProductCreateRequest.AttributesEntry
	nil,                              // 25: pim.ProductUpdateRequest.AttributesEntry
	nil,                              // 26: pim.Variant.AttributesEntry
	nil,                              // 27: pim.VariantCreateRequest.AttributesEntry
	nil,                              // 28: pim.VariantUpdateRequest.AttributesEntry
	(*timestamppb.Timestamp)(nil),    // 29: google.protobuf.Timestamp
}
var file_proto_pim_proto_depIdxs = []int32{
	3,  // 0: pim.ErrorResponse.error:type_name -> pim.ErrorDetail
	22, // 1: pim.ErrorDetail.details:type_name -> pim.ErrorDetail.DetailsEntry
	23, // 2: pim.Product.attributes:type_name -> pim.Product.AttributesEntry
	29, // 3: pim.Product.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: pim.Product.updated_at:type_name -> google.protobuf.Timestamp
	24, // 5: pim.ProductCreateRequest.attributes:type_name -> pim.ProductCreateRequest.AttributesEntry
	25, // 6: pim.ProductUpdateRequest.attributes:type_name -> pim.ProductUpdateRequest.AttributesEntry
	4,  // 7: pim.ProductListResponse.products:type_name -> pim.Product
	1,  // 8: pim.ProductListResponse.pagination:type_name -> pim.Pagination
	26, // 9: pim.Variant.attributes:type_name -> pim.Variant.AttributesEntry
	29, // 10: pim.Variant.created_at:type_name -> google.protobuf.Timestamp
	29, // 11: pim.Variant.updated_at:type_name -> google.protobuf.Timestamp
	27, // 12: pim.VariantCreateRequest.attributes:type_name -> pim.VariantCreateRequest.AttributesEntry
	28, // 13: pim.VariantUpdateRequest.attributes:type_name -> pim.VariantUpdateRequest.AttributesEntry
	8,  // 14: pim.VariantListResponse.variants:type_name -> pim.Variant
	29, // 15: pim.MediaAsset.created_at:type_name -> google.protobuf.Timestamp
	29, // 16: pim.MediaAsset.updated_at:type_name -> google.protobuf.Timestamp
	12, // 17: pim.MediaAssetListResponse.media_assets:type_name -> pim.MediaAsset
	17, // 18: pim.ProductType.attribute_definitions:type_name -> pim.AttributeDefinition
	29, // 19: pim.ProductType.created_at:type_name -> google.protobuf.Timestamp
	29, // 20: pim.ProductType.updated_at:type_name -> google.protobuf.Timestamp
	29, // 21: pim.AttributeDefinition.created_at:type_name -> google.protobuf.Timestamp
	19, // 22: pim.ProductTypeCreateRequest.attribute_definitions:type_name -> pim.AttributeDefinitionInput
	19, // 23: pim.ProductTypeUpdateRequest.attribute_definitions:type_name -> pim.AttributeDefinitionInput
	16, // 24: pim.ProductTypeListResponse.product_types:type_name -> pim.ProductType
	0,  // 25: pim.Product.AttributesEntry.value:type_name -> pim.AttributeValue
	0,  // 26: pim.ProductCreateRequest.AttributesEntry.value:type_name -> pim.AttributeValue
	0,  // 27: pim.ProductUpdateRequest.AttributesEntry.value:type_name -> pim.AttributeValue
	0,  // 28: pim.Variant.AttributesEntry.value:type_name -> pim.AttributeValue
	0,  // 29: pim.VariantCreateRequest.AttributesEntry.value:type_name -> pim.AttributeValue
	0,  // 30: pim.VariantUpdateRequest.AttributesEntry.value:type_name -> pim.AttributeValue
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_pim_proto_init() }
func file_proto_pim_proto_init() {
	if File_proto_pim_proto != nil {
		return
	}
	file_proto_pim_proto_msgTypes[0].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_NumberValue)(nil),
		(*AttributeValue_BooleanValue)(nil),
		(*AttributeValue_DateValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pim_proto_rawDesc), len(file_proto_pim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pim_proto_goTypes,
		DependencyIndexes: file_proto_pim_proto_depIdxs,
		MessageInfos:      file_proto_pim_proto_msgTypes,
	}.Build()
	File_proto_pim_proto = out.File
	file_proto_pim_proto_goTypes = nil
	file_proto_pim_proto_depIdxs = nil
}
